-- Insert sample monasteries in Sikkim
INSERT INTO public.monasteries (
  name, 
  description, 
  location, 
  latitude, 
  longitude, 
  altitude,
  founded_year,
  tradition,
  main_deity,
  significance,
  visiting_hours,
  entry_fee,
  contact_info,
  images,
  virtual_tour_url,
  audio_guide_urls
) VALUES 
(
  'Rumtek Monastery',
  'The Dharma Chakra Centre, also known as Rumtek Monastery, is a gompa located in the Indian state of Sikkim near the capital Gangtok. It is the largest monastery in Sikkim and is the seat-in-exile of the Gyalwang Karmapa.',
  'Rumtek, East Sikkim',
  27.3167,
  88.5833,
  1547,
  1966,
  'Kagyu',
  'Karmapa',
  'Seat-in-exile of the Gyalwang Karmapa, head of the Karma Kagyu lineage',
  '6:00 AM - 6:00 PM',
  'Free',
  '{"phone": "+91-3592-252023", "email": "info@rumtek.org"}',
  '["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"]',
  '/virtual-tours/rumtek',
  '{"en": "/audio/rumtek-en.mp3", "hi": "/audio/rumtek-hi.mp3", "ne": "/audio/rumtek-ne.mp3"}'
),
(
  'Enchey Monastery',
  'Enchey Monastery is located on a hilltop above Gangtok. Built in 1909, it belongs to the Nyingma order of Vajrayana Buddhism and is an important seat of the Nyingma order.',
  'Gangtok, East Sikkim',
  27.3389,
  88.6065,
  1840,
  1909,
  'Nyingma',
  'Guru Padmasambhava',
  'Important seat of the Nyingma order with annual Cham dance festival',
  '5:00 AM - 7:00 PM',
  'Free',
  '{"phone": "+91-3592-202697"}',
  '["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"]',
  '/virtual-tours/enchey',
  '{"en": "/audio/enchey-en.mp3", "hi": "/audio/enchey-hi.mp3", "ne": "/audio/enchey-ne.mp3"}'
),
(
  'Pemayangtse Monastery',
  'Pemayangtse Monastery is a Buddhist monastery in Pemayangtse, near Pelling in the northeastern Indian state of Sikkim. Planned, designed and founded by Lama Lhatsun Chempo in 1705.',
  'Pemayangtse, West Sikkim',
  27.2167,
  88.2167,
  2085,
  1705,
  'Nyingma',
  'Guru Rinpoche',
  'One of the oldest and premier monasteries of Sikkim, head monastery of Nyingma order',
  '7:00 AM - 5:00 PM',
  'Rs. 10 for Indians, Rs. 20 for foreigners',
  '{"phone": "+91-3595-250298"}',
  '["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"]',
  '/virtual-tours/pemayangtse',
  '{"en": "/audio/pemayangtse-en.mp3", "hi": "/audio/pemayangtse-hi.mp3", "ne": "/audio/pemayangtse-ne.mp3"}'
),
(
  'Tashiding Monastery',
  'Tashiding Monastery is a Buddhist monastery of the Nyingma sect of Tibetan Buddhism in Western Sikkim. It is located on top of the hill rising between the Rathong chu and the Rangeet River.',
  'Tashiding, West Sikkim',
  27.2833,
  88.2667,
  1465,
  1641,
  'Nyingma',
  'Guru Padmasambhava',
  'Sacred site where Guru Padmasambhava blessed the land, famous for Bhumchu festival',
  '6:00 AM - 6:00 PM',
  'Free',
  '{"phone": "+91-3595-250199"}',
  '["/placeholder.svg?height=400&width=600", "/placeholder.svg?height=400&width=600"]',
  '/virtual-tours/tashiding',
  '{"en": "/audio/tashiding-en.mp3", "hi": "/audio/tashiding-hi.mp3", "ne": "/audio/tashiding-ne.mp3"}'
);
